permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: whdcumt
  email: wanghongdong0@126.com
  link: whdcumt.github.io
  weibo: http://weibo.com/u/2102405092/home?wvr=5&sudaref=www.so.com&retcode=6102
  github: 
  music: 
  linkedin: 

# 站点信息
title: 王洪栋的博客
description: My personal blog
url: http://painterlin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/bolt.png
favicon: /public/img/bolt.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档